version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Comp9900
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization SQL script

    # Run SQL Server and initialize the database using `init.sql`
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 30s
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123 -i /docker-entrypoint-initdb.d/init.sql
