services:
  app:
    build: 
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - APP_ENV=local
    healthcheck:
      test: "curl -f http://localhost:5001/heartbeat/readiness || exit 1"
      interval: 20s
      timeout: 3s
      retries: 15
    volumes:
      - ./..:/usr/scr/app
    networks:
      - ns

networks:
  ns:
    driver: bridge